src/Entity/Painting.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use App\Repository\PaintingRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


#[ORM\Entity(repositoryClass: PaintingRepository::class)]
#[Vich\Uploadable]
class Painting
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $author = null;

    #[ORM\Column]
    private ?int $height = null;

    #[ORM\Column]
    private ?int $width = null;

    #[Vich\UploadableField(mapping: 'paints_images', fileNameProperty: 'image_name')]
    private ?File $imageFile = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image_name = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\ManyToOne(inversedBy: 'paintings')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Technic $technic = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\Column(length: 255)]
    private ?string $date = null;

    #[ORM\Column]
    private ?int $rarityScore = null;

    #[ORM\Column]
    private ?bool $visible = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $updatedAt = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getHeight(): ?int
    {
        return $this->height;
    }

    public function setHeight(int $height): self
    {
        $this->height = $height;

        return $this;
    }

    public function getWidth(): ?int
    {
        return $this->width;
    }

    public function setWidth(int $width): self
    {
        $this->width = $width;

        return $this;
    }

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getImageName(): ?string
    {
        return $this->image_name;
    }

    public function setImageName(?string $image_name): self
    {
        $this->image_name = $image_name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getTechnic(): ?technic
    {
        return $this->technic;
    }

    public function setTechnic(?technic $technic): self
    {
        $this->technic = $technic;

        return $this;
    }

    public function getCategory(): ?category
    {
        return $this->category;
    }

    public function setCategory(?category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getDate(): ?string
    {
        return $this->date;
    }

    public function setDate(string $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getRarityScore(): ?int
    {
        return $this->rarityScore;
    }

    public function setRarityScore(int $rarityScore): self
    {
        $this->rarityScore = $rarityScore;

        return $this;
    }

    public function isVisible(): ?bool
    {
        return $this->visible;
    }

    public function setVisible(bool $visible): self
    {
        $this->visible = $visible;

        return $this;
    }

    public function createSlug()
    {
        $slugify = new Slugify();
        $this->slug = $slugify->slugify($this->title);
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

}

templates/pages/about.html.twig
{% extends 'base.html.twig' %}
{% block title %} La gallerie {% endblock %}
{% block body %}
<div class="container about">
    <div class="row text-center mt-5">
        <h1>Le musée</h1>
        <hr>
    </div>
    <div class="row about-1">
        <div class="col-12 col-md-5 about-text-1">
            <p>Le Musée du Louvre est l'un des plus grands musées du monde, situé en plein centre de Paris dans le 1er arrondissement. Près de 35 000 objets, de la préhistoire au 21e siècle, y sont exposées sur une superficie de 60 600 m². Avec plus de 8 millions de visiteurs chaque année, il est le musée le plus visité au monde.

                Le musée est situé dans le Palais du Louvre, jadis forteresse construite à la fin du 12ème siècle sous Philippe II. Les vestiges de la forteresse sont visibles dans le sous-sol du musée. Le bâtiment a été agrandi plusieurs fois pour former l'actuel Palais du Louvre. En 1682, Louis XIV choisit le château de Versailles pour y loger, laissant le Louvre principalement comme un endroit pour afficher la collection royale. En 1692, le bâtiment a été occupé par l'Académie des Inscriptions et Belles-Lettres et l'Académie Royale de Peinture et de Sculpture, qui a tenu la première d'une série de salons en 1699. L'Académie est restée au Louvre pendant 100 ans. Pendant la Révolution française, l'Assemblée Nationale a décrété que le Louvre devait être utilisé comme un musée, afin d'afficher les chefs-d'œuvre de la nation.</p>
        </div>
        <div class="col-12 col-md-7 about-img-1">
        </div>
    </div>
    <hr>
    <div class="row about-2">
        <div class="col-12 col-md-7 about-img-2">
        </div>
        <div class="col-12 col-md-5 about-text-2 p-5">
            <p>Le musée a ouvert le 10 Août 1793 avec une exposition de 537 peintures, la majorité des travaux étant royal et les biens confisqués à l'église. En raison de problèmes structurels de l'immeuble, le musée a été fermé en 1796 jusqu'en 1801. La taille de la collection a augmenté sous Napoléon et le musée a été rebaptisé le Musée Napoléon. Après la défaite de Napoléon à Waterloo, de nombreux ouvrages saisis par ses armées ont été restitués à leurs propriétaires d'origine. La collection a été encore augmentée pendant les règnes de Louis XVIII et Charles X, et pendant le Second Empire français, le musée a gagné 20 000 pièces.

                En 2008, la collection est répartie entre huit départements de conservation: Antiquités égyptiennes, Antiquités orientales, Antiquités grecques, étrusques et romaines, Arts de l'Islam, sculpture, les arts décoratifs, des peintures, estampes et dessins.</p>
        </div>
    </div>
</div>
{% endblock %}

templates/pages/gallery.html.twig
{% extends 'base.html.twig' %}
{% block title %} Gallerie - Le Louvre {% endblock %}
{% block body %}
    <div class="container gallery">
        <div class="row text-center mt-5">
            <h1>Notre gallerie</h1>
            <hr>
        </div>
        <div class="col-md-12 controls-filter text-center">
            <ul>
                <!-- For filtering controls add -->
                <li data-filter="all" class="btn btn-outline-primary"> Toutes les peintures </li>
                <br><br>
                {% for category in categories %}
                    <li data-filter="{{ category.id }}" class="btn btn-outline-primary">{{ category.name }}</li>
                {% endfor %}
                <br><br>
                {% for technic in technics %}
                    <li data-filter="{{ technic.id }}" class="btn btn-outline-primary">{{ technic.name }}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="filter-container" style="overflow: hidden">
            <div class="row main-galery" style="overflow: hidden">
                {% for paints in paintings %}
                    <div class="filtr-item col-12 col-sm-6 col-md-4 card" data-category="{{ paints.category.id }}, {{
                    paints.technic.id }}"
                         data-sort="value" style="overflow: hidden">
                            <div class="card-img">
                                <a href="#"><img src="{{ asset('img/paints/' ~ paints.imageName) }}"
                                                 class="card-img-top" alt="..."></a>
                            </div>
                            <div class="card-body text-center">
                                <h5 class="card-title"><b>{{ paints.title }}</b></h5>
                                <h6 class="card-author"><b>Auteur:</b> {{ paints.author }}</h6>
                                <h6 class="card-date"><b>Date:</b> {{ paints.date }}</h6>
                                <a href="{{ path('paint', {slug:paints.slug}) }}" class="btn btn-primary">En savoir
                                    plus</a>
                            </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <script src="{{ asset('js/jquery.min.js') }}"></script>
    <script src="{{ asset('js/jquery.filterizr.min.js') }}"></script>
    <script>
        let filterizd = $('.filter-container').filterizr({
            // options here
        });
    </script>
{% endblock %}

templates/pages/paint.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<div class="container-fluid back-paint text-center">
    {% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}
    <div class="container paint pb-5">
        <div class="row text-center">
            <h1>{{ painting.title }}</h1>
            <hr>
        </div>
        <div class="row">
            <div class="card col-12 col-md-6">
                <img class="card-img-top" src="{{ asset('img/paints/' ~ painting.imageName) }}" alt="">
            </div>
            <div class="description col-12 col-md-6 align-middle">
                <p>{{ painting.description }}</p>
                <p><b>Auteur:</b> {{ painting.author }}</p>
                <p><b>Date:</b> {{ painting.date }}</p>
                <p><b>Dimensions originales:</b> {{ painting.height }} x {{ painting.width }}</p>
            </div>
        </div>
    </div>
    <div class="container comment">
        <div class="row">
            <h1>Commentaires</h1>
            <hr>
            <main class="container ">
                <div class="row justify-content-between">
                    <div class="comments m-2 col-12 col-md-6 text-center">
                        <h4 class="mt-3">Commentaires</h4>
                        <hr>
                        {% if comments|length >= 1 %}
                        {% for comment in comments  %}
                            <i>"{{ comment.content }}"</i>
                            <p class="comment-author">{{ comment.author }}  ({{ comment.date|date('d-m-Y h:i')}})
                            </p><hr>
                        {% endfor %}
                        {% else %}
                            <p>Aucun commentaire pour le moment!</p>
                        {% endif %}
                    </div>
                    <div class="form-group shadow-textarea col-12 col-md-4 m-2">
                        <h2 class="display-6 my-3">Ajouter un commentaire</h2>
                        {{ form_start(form) }}
                        {{ form_widget(form) }}
                        <button type="submit" class="btn btn-light">Confirmer</button>
                        {{ form_end(form) }}
                    </div>
                </div>
            </main>
        </div>
</div>

{% endblock %}

templates/pages/team.html.twig
{% extends 'base.html.twig' %}
{% block title %}Gouvernance - Le Louvre {% endblock %}
{% block body %}
    <div class="container gallery">
        <div class="row text-center mt-5">
            <h1>Gouvernance</h1>
            <hr>
        </div>
        <div class="container team">
            <div class="row">
                {% for member in members %}
                    <div class="card col-6 col-md-4 col-lg-3 col-sm-6 team">
                        <img class="card-img-top" src="{{ asset('img/team/'  ~ member.image) }}" alt="Card image cap">
                        <div class="card-body text-center">
                            <h5 class="card-title">{{ member.fullname }}</h5>
                            <p class="card-text">{{ member.job }}</p>
                        </div>
                        <div class="card-body text-center">
                            <a href="#" class="card-link"><i class="icofont-instagram"></i></a>
                            <a href="#" class="card-link"><i class="icofont-linkedin"></i></a>
                            <a href="#" class="card-link"><i class="icofont-pinterest"></i></i></a>
                            <a href="#" class="card-link"><i class="icofont-rss"></i></a>
                            <a href="#" class="card-link"><i class="icofont-blogger"></i></a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}